SELECT II.ITEM_ID,
       II.ITEM_NAME,
       II.RARITY
  FROM ITEM_INFO II
 WHERE II.ITEM_ID NOT IN (
       SELECT PARENT_ITEM_ID
         FROM ITEM_TREE
        where PARENT_ITEM_ID is not null
       )
 ORDER BY II.ITEM_ID DESC;