SELECT 
    EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
    (MAX_YEAR_SIZE.SIZE_OF_COLONY - ED.SIZE_OF_COLONY) AS YEAR_DEV,
    ED.ID
FROM 
    ECOLI_DATA ED
JOIN 
    (SELECT 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
     FROM 
        ECOLI_DATA
     GROUP BY 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
    ) AS MAX_YEAR_SIZE
ON 
    EXTRACT(YEAR FROM ED.DIFFERENTIATION_DATE) = MAX_YEAR_SIZE.YEAR
ORDER BY 
    YEAR ASC, YEAR_DEV ASC;