SELECT 
    T.SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) AS T
JOIN HR_EMPLOYEES E 
  ON T.EMP_NO = E.EMP_NO
WHERE T.SCORE = (
    SELECT MAX(X.SCORE)
    FROM (
        SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) X
);
